version: '3'
services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
  backend:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.10
    ports:
      - "8000:80"
    volumes:
      - .:/app
    command: uvicorn backend:app --host 0.0.0.0 --port 80
    env_file:
      - .env