import streamlit as st

st.title("💸 Pricing Plans")
st.info("Choose the plan that suits your needs.")

st.markdown("""
### 🔓 Free Plan
- 📁 Upload and Analyze Tally CSV: ✅
- 📊 Summary Metrics & Charts: ✅
- 🔄 Monthly Revenue Trend: ✅
- 📈 AI Forecasting: ❌
- 🧠 GPT Financial Advisor: ❌
- 🤖 FinGPT AI Analyst: ❌
- 💡 FinRL Smart Recommendation: ❌
- 📥 Report Downloads (PDF/Excel): ❌
- 💬 Telegram Alerts: ❌
- Price: ₹0/month

---

### 💼 Pro Plan
- 📁 Upload and Analyze Tally CSV: ✅
- 📊 Summary Metrics & Charts: ✅
- 🔄 Monthly Revenue Trend: ✅
- 📈 AI Forecasting: ✅
- 🧠 GPT Financial Advisor: ✅
- 🤖 FinGPT AI Analyst: ✅
- 💡 FinRL Smart Recommendation: ✅
- 📥 Report Downloads (PDF/Excel): ✅
- 💬 Telegram Alerts: ✅
- ⚙️ Priority Feature Access: ✅
- Price: ₹999/month
""")

st.markdown("---")
st.markdown("💳 Ready to unlock the full potential? [Upgrade to Pro from your Dashboard](#)")
